name: Build FakeCam Dylib Fast

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Chuyển sang Linux để không phải xếp hàng chờ máy macOS

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4

    - name: Thiết lập môi trường Linux và Theos
      run: |
        sudo apt-get update
        sudo apt-get install -y clang build-essential git perl libssl-dev
        bash -c "$(curl -fsSL https://githubusercontent.com)"
        echo "THEOS=~/theos" >> $GITHUB_ENV
        
    - name: Tải iOS SDK
      run: |
        git clone https://github.com ~/theos/sdks
        
    - name: Tiến hành Biên dịch Tweak Chống Văng
      run: |
        export THEOS=~/theos
        make package FINALPACKAGE=1
        
    - name: Lưu trữ file dylib kết quả
      uses: actions/upload-artifact@v4
      with:
        name: libfakecampicker-dylib
        path: .theos/obj/debug/libfakecampicker.dylib
